name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags:
      - '!**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: yarn

      - name: Install dependencies
        run: yarn install

      - name: Run tests, lint and verify package integrity
        run: yarn run validate
